name: slashWild
main: LEET\Wild
version: 1.0dev
api: [2.0.0, 2.1.0, 3.0.0]
load: STARTUP
author: eDroid and RTGNetworkkk
description: slashWild, a new and improved way to be teleported somewhere wild

commands:
 wild:
  aliases: [tprandom]
  description: teleport somewhere random and wild!
  permission: slashWild.command.wild

permissions:
  slashWild.command.wild:
    default: true
    description: /wild main permission
